from torch_geometric.nn import SAGEConv,GCNConv


default_config={
    "n_eighborss" : 15,
    "n_top_genes" : 2000,
    "hidden_dim" : 64,
    "latent_dim" : 64,
    "conv_layer" :SAGEConv,
    "epochs_cluster" : 300,
    "pre_epoch":200,
    "lr_cluster" : 0.001}


configs={
"Adam":{
    "n_eighborss" : 15,
    "n_top_genes" : 2000,
    "hidden_dim" : 256,
    "latent_dim" : 32,
    "conv_layer" :SAGEConv,
    "epochs_cluster" : 800,
    "pre_epoch":500,
    "lr_cluster" : 0.0001},
    "Muraro":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 64,
        "latent_dim" : 64,
        "conv_layer" :SAGEConv,
        "epochs_cluster" : 500,
        "pre_epoch":200,
        "lr_cluster" : 0.001},
    "Bach":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 128,
        "latent_dim" : 32,
        "conv_layer" :SAGEConv,
        "epochs_cluster" : 500,
        "pre_epoch":200,
        "lr_cluster" : 0.005},
    "Campbell":default_config,
    "Cao_2020_Spleen":default_config,
    "Quake_10x_Bladder":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 128,
        "latent_dim" : 32,
        "conv_layer" :SAGEConv,
        "epochs_cluster" : 500,
        "pre_epoch":200,
        "lr_cluster" : 0.005},
    "Quake_10x_Limb_Muscle":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 128,
        "latent_dim" : 128,
        "conv_layer" :SAGEConv,
        "epochs_cluster" : 500,
        "pre_epoch":200,
        "lr_cluster" : 0.001},
    "Quake_10x_Spleen":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 128,
        "latent_dim" : 32,
        "conv_layer" :SAGEConv,
        "epochs_cluster" : 300,
        "pre_epoch":200,
        "lr_cluster" : 0.005},
    "Quake_Smart-seq2_Diaphragm":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 64,
        "latent_dim" : 64,
        "conv_layer" :GCNConv,
        "epochs_cluster" : 500,
        "pre_epoch":200,
        "lr_cluster" : 0.0001},
    "Quake_Smart-seq2_Limb_Muscle":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 64,
        "latent_dim" : 32,
        "conv_layer" :SAGEConv,
        "epochs_cluster" : 300,
        "pre_epoch":200,
        "lr_cluster" : 0.001},
    "Quake_Smart-seq2_Lung":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 512,
        "latent_dim" : 512,
        "conv_layer" :SAGEConv,
        "epochs_cluster" : 500,
        "pre_epoch":200,
        "lr_cluster" : 0.001},
    "Quake_Smart-seq2_Trachea":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 64,
        "latent_dim" : 32,
        "conv_layer" :GCNConv,
        "epochs_cluster" : 800,
        "pre_epoch":500,
        "lr_cluster" : 0.005},
    "Romanov":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 128,
        "latent_dim" : 512,
        "conv_layer" :SAGEConv,
        "epochs_cluster" : 500,
        "pre_epoch":200,
        "lr_cluster" : 0.001},
    "Shekhar":default_config,

    "Tosches_turtle":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 128,
        "latent_dim" : 32,
        "conv_layer" :GCNConv,
        "epochs_cluster" : 800,
        "pre_epoch":500,
        "lr_cluster" : 0.005},

        "Wang_Large_Intestine":{
        "n_eighborss" : 15,
        "n_top_genes" : 2000,
        "hidden_dim" : 512,
        "latent_dim" : 512,
        "conv_layer" :GCNConv,
        "epochs_cluster" : 300,
        "pre_epoch":200,
        "lr_cluster" : 0.0001} ,
        "Young":default_config
    }